# Generated by Django 4.2.7 on 2023-12-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfield',
            name='analyzer_id',
        ),
        migrations.RemoveField(
            model_name='deviceinfield',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='deviceinfield',
            name='analyzer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='orders_app.device', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='deviceinfield',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='orders_app.customer', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.TextField(choices=[('open', 'открыта'), ('closed', 'закрыта'), ('in progress', 'в работе'), ('need info', 'нужна информация')], null=True, verbose_name='Статус заявки'),
        ),
    ]
